[package]
name = "spiral"
version = "0.1.0"
edition = "2021"

[dependencies]
ropey = "1"
mlua = { version = "0.9", features = ["luau"] }
log = "0.4"
env_logger = "0.11"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ratatui = "0.28"
dirs = "5"
