[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
clap = { version = "4", features = ["derive"] }
ratatui = "0.28"
log = "0.4"
env_logger = "0.11"
